# Configuration for Travis CI
# See https://travis-ci.org/syndibot/syndi

language: ruby
rvm:
  - 2.0.0
before_install: gem install bundler --pre

# Notify the official IRC channel
# i.e. irc.freenode.net #syndi
notifications:
  email:
    on_success: never
    on_failure: never
  irc:
    channels:
      - 'irc.freenode.net#syndi'
    on_success: change
    on_failure: always
    template:
      - "%{repository} #%{build_number} (%{branch} - %{commit}: %{author}): %{message}"
      - "Build details: %{build_url}"
