# Configuration for Travis CI
# See https://travis-ci.org/Auto/Auto

language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - rbx-19mode
  - jruby-19mode

# Notify the official IRC channel
# i.e. irc.freenode.net #auto
notifications:
  irc:
    channels:
      - 'irc.freenode.net#auto'
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch} - %{commit}: %{author}): %{message}"
      - "Build details: %{build_url}"
